schema_version = "1.0.0"
id = "customboneproperty"
name = "Custom Bone Property"
tagline = "Adds/Removes a custom property to each bone in the active armature"
type = "add-on"
tags = [ "Blastframe","Armature","Rigging"]
version = "1.0.0"
blender_version_min = "4.2.0"
maintainer = "Blastframe"
website = "https://blastframe.com/"
license = [ "SPDX:GPL-2.0-or-later",]
copyright = [ "© 2025 Blastframe. All rights reserved.",]
